name: test workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gbrls/action-dropbox-download@main
        with:
          dropbox-token: ${{ secrets.DROPBOX_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

