name: test workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gbrls/action-dropbox-download@main
        with:
          dropbox-sl-token: ${{ secrets.DROPBOX_SL_TOKEN }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: '/dotfiles/zk'
          destination-path: 'downloaded'
      - name: List artifacts
        run: |
          ls -la
          find

